package com.bezkoder.spring.security.postgresql.util.mailAndpdf;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import com.bezkoder.spring.security.postgresql.dto.mail.MailDTO;
import com.bezkoder.spring.security.postgresql.util.email.smtp.MailSender;
import com.bezkoder.spring.security.postgresql.util.propertyfile.ContextConstants;

/**
 * @Generate pdf files for reports
 * @author Siya
 *
 */
public class RegisteredUsersMail {

	public static void registeredUsers(MailDTO mailDTO) {
		// TODO Auto-generated method stub

		List<String> bcc = new ArrayList<String>();
		List<String> cc = new ArrayList<String>();
		List<String> to = new ArrayList<String>();
		List<String> files = new ArrayList<String>();
		String bodymsg = "Hi " + mailDTO.getName() + ", Thank you for registering ,your account has been successfully setup."
				+ "To login to your account please go to our main site and enter your account information."
				+ "Your Username is :" + mailDTO.getUsername() + " and Your password is : " + mailDTO.getPassword();

		Calendar calender = Calendar.getInstance();
		Date currDate = calender.getTime();
		to.add(mailDTO.getMailId());

		String mailContent = "  <div style='background-color:#d6d6d5;margin:0;min-width:100%;padding:0;width:100%'> "
				+ "    			   <table width='100%' border='0' cellpadding='0' cellspacing='0' style='background-color:#d6d6d5;border:none;border-collapse:collapse;border-spacing:0;width:100%' bgcolor='#d6d6d5'> "
				+ "    			     <tbody> " + "    			       <tr> "
				+ "    			         <td align='center'> "
				+ "    			           <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;max-width:700px;width:100%'> "
				+ "    			             <tbody> " + "    			               <tr> "
				+ "    			                 <td style='background-color:#ffffff' align='center'> "
				+ "    			                   <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;margin:auto;max-width:700px;width:100%'> "
				+ "    			                     <tbody> " + "    			                       <tr> "
				+ "    			                         <td align='center'> "
				+ "    			                           <table width='100%' border='0' cellpadding='0' cellspacing='0' style='background-color:#ffffff;border:none;border-collapse:collapse;border-spacing:0;margin:auto;width:100%' bgcolor='#ffffff'> "
				+ "    			                             <tbody> "
				+ "    			                               <tr> "
				+ "    			                                 <td align='center'> "
				+ "    			                                   <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                     <tbody> "
				+ "    			                                       <tr> "
				+ "    			                                         <td align='center' style='background-color:#ffffff'> "
				+ "    			                                           <table border='0' cellpadding='0' cellspacing='0' width='100%' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                             <tbody> "
				+ "    			                                               <tr> "
				+ "    			                                                 <td> "
				+ "    			                                                   <table border='0' cellpadding='0' cellspacing='0' width='100%' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                     <tbody> "
				+ "    			                                                       <tr> "
				+ "    			                                                         <td bgcolor='#ffffff'> "
				+ "    			                                                           <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                             <tbody> "
				+ "    			                                                               <tr> "
				+ "    			                                                                 <td align='left' style='direction:ltr;text-align:left'> "
				+ "    			                                                                   <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                     <tbody> "
				+ "    			                                                                       <tr> "
				+ "    			                                                                         <td bgcolor='#D9E8AF' style='direction:ltr;text-align:left'> "
				+ "    			                                                                           <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                             <tbody> "
				+ "    			                                                                               <tr> "
				+ "    			                                                                                 <td width='14' style='direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                                 <td align='left' style='direction:ltr;text-align:left'> "
				+ "    			                                                                                   <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                                     <tbody> "
				+ "    			                                                                                       <tr> "
				+ "    			                                                                                         <td align='center'> "
				+ "    			                                                                                           <table border='0' cellpadding='0' cellspacing='0' align='center' style='border:none;border-collapse:collapse;border-spacing:0;max-width:616px;width:100%'> "
				+ "    			                                                                                             <tbody> "
				+ "    			                                                                                               <tr> "
				+ "    			                                                                                                 <td align='center' style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important'> "
				+ "    			                                                                                                   <table border='0' cellpadding='0' cellspacing='0' align='center' style='border:none;border-collapse:collapse;border-spacing:0;max-width:560px;width:100%'> "
				+ "    			                                                                                                     <tbody> "
				+ "    			                                                                                                       <tr> "
				+ "    			                                                                                                         <td width='12' style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                                                         <td style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'> "
				+ "    			                                                                                                           <table border='0' cellpadding='0' cellspacing='0' width='100%' align='left' style='border:none;border-collapse:collapse;border-spacing:0;table-layout:fixed;width:100%'> "
				+ "    			                                                                                                             <tbody> "
				+ "    			                                                                                                               <tr> "
				+ "    			                                                                                                                 <td style='direction:ltr;text-align:left'> "
				+ "    			                                                                                                                   <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                                                                     <tbody> "
				+ "    			                                                                                                                       <tr> "
				+ "    			                                                                                                                         <td align='left' style='padding-top:45px;padding-bottom:40px;direction:ltr;text-align:left' valign='middle'> "
				+ "    			                                                                                                                           <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                                                                             <tbody> "
				+ "    			                                                                                                                               <tr> "
				+ "    			                                                                                                                                 <td valign='top' align='left' style='color:rgb(0,0,0);font-family:Helvetica,Arial,sans-serif;font-size:30px;line-height:30px;padding-right:12px;padding-top:5px;direction:ltr;text-align:left'></td> "
				+ "    			                                                                                                                                 <td width='80%' align='right' style='color:rgb(0,0,0);font-family:Helvetica,Arial,sans-serif;font-size:12px;line-height:18px;text-align:right;direction:ltr' valign='middle'> "
				+ "    			                                                                                                                                   <span style='color:#000000;font-family:Helvetica,Arial,sans-serif;font-size:12px;line-height:15px'> "
				+ currDate + " </span> "
				+ "    			                                                                                                                                 </td> "
				+ "    			                                                                                                                               </tr> "
				+ "    			                                                                                                                             </tbody> "
				+ "    			                                                                                                                           </table> "
				+ "    			                                                                                                                         </td> "
				+ "    			                                                                                                                       </tr> "
				+ "    			                                                                                                                     </tbody> "
				+ "    			                                                                                                                   </table> "
				+ "    			                                                                                                                 </td> "
				+ "    			                                                                                                               </tr> "
				+ "    			                                                                                                             </tbody> "
				+ "    			                                                                                                           </table> "
				+ "    			                                                                                                         </td> "
				+ "    			                                                                                                         <td width='12' style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                                                       </tr> "
				+ "    			                                                                                                     </tbody> "
				+ "    			                                                                                                   </table> "
				+ "    			                                                                                                 </td> "
				+ "    			                                                                                               </tr> "
				+ "    			                                                                                             </tbody> "
				+ "    			                                                                                           </table> "
				+ "    			                                                                                         </td> "
				+ "    			                                                                                       </tr> "
				+ "    			                                                                                     </tbody> "
				+ "    			                                                                                   </table> "
				+ "    			                                                                                 </td> "
				+ "    			                                                                                 <td width='14' style='direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                               </tr> "
				+ "    			                                                                             </tbody> "
				+ "    			                                                                           </table> "
				+ "    			                                                                         </td> "
				+ "    			                                                                       </tr> "
				+ "    			                                                                     </tbody> "
				+ "    			                                                                   </table> "
				+ "    			                                                                 </td> "
				+ "    			                                                               </tr> "
				+ "    			                                                             </tbody> "
				+ "    			                                                           </table> "
				+ "    			                                                           <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                             <tbody> "
				+ "    			                                                               <tr> "
				+ "    			                                                                 <td align='left' style='direction:ltr;text-align:left'> "
				+ "    			                                                                   <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                     <tbody> "
				+ "    			                                                                       <tr> "
				+ "    			                                                                         <td  bgcolor='#D9E8AF' width='700' valign='top' style='background-repeat:no-repeat;background-position:right bottom;direction:ltr;text-align:left'> "
				+ "    			                                                                           <div> "
				+ "    			                                                                             <div style='font-size:0;line-height:0'> "
				+ "    			                                                                               <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                                 <tbody> "
				+ "    			                                                                                   <tr> "
				+ "    			                                                                                     <td width='14' style='direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                                     <td align='left' style='direction:ltr;text-align:left'> "
				+ "    			                                                                                       <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                                         <tbody> "
				+ "    			                                                                                           <tr> "
				+ "    			                                                                                             <td align='center'> "
				+ "    			                                                                                               <table border='0' cellpadding='0' cellspacing='0' align='center' style='border:none;border-collapse:collapse;border-spacing:0;max-width:616px;width:100%'> "
				+ "    			                                                                                                 <tbody> "
				+ "    			                                                                                                   <tr> "
				+ "    			                                                                                                     <td align='center' style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important'> "
				+ "    			                                                                                                       <table border='0' cellpadding='0' cellspacing='0' align='center' style='border:none;border-collapse:collapse;border-spacing:0;max-width:560px;width:100%'> "
				+ "    			                                                                                                         <tbody> "
				+ "    			                                                                                                           <tr> "
				+ "    			                                                                                                             <td width='12' style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                                                             <td style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'> "
				+ "    			                                                                                                               <table border='0' cellpadding='0' cellspacing='0' width='100%' align='left' style='border:none;border-collapse:collapse;border-spacing:0;table-layout:fixed;width:100%'> "
				+ "    			                                                                                                                 <tbody> "
				+ "    			                                                                                                                   <tr> "
				+ "    			                                                                                                                     <td style='direction:ltr;text-align:left'> "
				+ "    			                                                                                                                       <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                                                                         <tbody> "
				+ "    			                                                                                                                           <tr> "
				+ "    			                                                                                                                             <td align='left' style='font-size:0px;direction:ltr;text-align:left'> "
				+ "    			                                                                                                                               <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;display:inline-block;max-width:392px;vertical-align:bottom;width:100%'> "
				+ "    			                                                                                                                                 <tbody> "
				+ "    			                                                                                                                                   <tr> "
				+ "    			                                                                                                                                     <td style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'> "
				+ "    			                                                                                                                                       <table border='0' cellpadding='0' cellspacing='0' width='100%' align='left' style='border:none;border-collapse:collapse;border-spacing:0;table-layout:fixed;width:100%'> "
				+ "    			                                                                                                                                         <tbody> "
				+ "    			                                                                                                                                           <tr> "
				+ "    			                                                                                                                                             <td style='color:rgb(0,0,0);font-family:Helvetica,Arial,sans-serif;font-size:34px;line-height:38px;padding-bottom:13px;direction:ltr;text-align:left'>"
				+ "Sayone Technology" + "</td> "
				+ "    			                                                                                                                                           </tr> "
				+ "    			                                                                                                                                           <tr> "
				+ "    			                                                                                                                                             <td style='color:rgb(0,0,0);font-family:Helvetica,Arial,sans-serif;font-size:16px;line-height:28px;direction:ltr;text-align:left'> "
				+ "    			                                                                                                                                               <table border='0' cellpadding='0' cellspacing='0' align='left' style='border:none;border-collapse:collapse;border-spacing:0;max-width:308px;width:100%'> "
				+ "    			                                                                                                                                                 <tbody> "
				+ "    			                                                                                                                                                   <tr> "
				+ "    			                                                                                                                                                     <td style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'> "
				+ "    			                                                                                                                                                     </td> "
				+ "    			                                                                                                                                                   </tr> "
				+ "    			                                                                                                                                                 </tbody> "
				+ "    			                                                                                                                                               </table> "
				+ "    			                                                                                                                                             </td> "
				+ "    			                                                                                                                                           </tr> "
				+ "    			                                                                                                                                         </tbody> "
				+ "    			                                                                                                                                       </table> "
				+ "    			                                                                                                                                     </td> "
				+ "    			                                                                                                                                   </tr> "
				+ "    			                                                                                                                                 </tbody> "
				+ "    			                                                                                                                               </table> "
				+ "    			                                                                                                                             </td> "
				+ "    			                                                                                                                           </tr> "
				+ "    			                                                                                                                         </tbody> "
				+ "    			                                                                                                                       </table> "
				+ "    			                                                                                                                     </td> "
				+ "    			                                                                                                                   </tr> "
				+ "    			                                                                                                                 </tbody> "
				+ "    			                                                                                                               </table> "
				+ "    			                                                                                                             </td> "
				+ "    			                                                                                                             <td width='12' style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                                                           </tr> "
				+ "    			                                                                                                         </tbody> "
				+ "    			                                                                                                       </table> "
				+ "    			                                                                                                     </td> "
				+ "    			                                                                                                   </tr> "
				+ "    			                                                                                                 </tbody> "
				+ "    			                                                                                               </table> "
				+ "    			                                                                                             </td> "
				+ "    			                                                                                           </tr> "
				+ "    			                                                                                         </tbody> "
				+ "    			                                                                                       </table> "
				+ "    			                                                                                     </td> "
				+ "    			                                                                                     <td width='14' style='direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                                   </tr> "
				+ "    			                                                                                 </tbody> "
				+ "    			                                                                               </table> "
				+ "    			                                                                             </div> "
				+ "    			                                                                           </div> "
				+ "    			                                                                         </td> "
				+ "    			                                                                       </tr> "
				+ "    			                                                                     </tbody> "
				+ "    			                                                                   </table> "
				+ "    			                                                                 </td> "
				+ "    			                                                               </tr> "
				+ "    			                                                             </tbody> "
				+ "    			                                                           </table> "
				+ "    			                                                           <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                             <tbody> "
				+ "    			                                                               <tr> "
				+ "    			                                                                 <td align='left' style='padding:0px 14px 0px 14px;direction:ltr;text-align:left'> "
				+ "    			                                                                   <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                     <tbody> "
				+ "    			                                                                       <tr> "
				+ "    			                                                                         <td style='direction:ltr;text-align:left'> "
				+ "    			                                                                           <table border='0' cellpadding='0' cellspacing='0' align='left' style='border:none;border-collapse:collapse;border-spacing:0;max-width:56px;width:100%'> "
				+ "    			                                                                             <tbody> "
				+ "    			                                                                               <tr> "
				+ "    			                                                                                 <td style='font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'> "
				+ "    			                                                                                   <table border='0' cellpadding='0' cellspacing='0' width='100%' align='left' style='border:none;border-collapse:collapse;border-spacing:0;table-layout:fixed;width:100%'> "
				+ "    			                                                                                     <tbody> "
				+ "    			                                                                                       <tr> "
				+ "    			                                                                                         <td style='font-size:1px;line-height:1px;height:1px;min-height:1px;direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                                       </tr> "
				+ "    			                                                                                     </tbody> "
				+ "    			                                                                                   </table> "
				+ "    			                                                                                 </td> "
				+ "    			                                                                               </tr> "
				+ "    			                                                                             </tbody> "
				+ "    			                                                                           </table> "
				+ "    			                                                                           <table border='0' cellpadding='0' cellspacing='0' align='left' style='border:none;border-collapse:collapse;border-spacing:0;max-width:616px;width:100%'> "
				+ "    			                                                                             <tbody> "
				+ "    			                                                                               <tr> "
				+ "    			                                                                                 <td style='padding-bottom:30px;padding-left:12px;padding-right:12px;direction:ltr;text-align:left'> "
				+ "    			                                                                                   <table border='0' cellpadding='0' cellspacing='0' width='100%' align='left' style='border:none;border-collapse:collapse;border-spacing:0;table-layout:fixed;width:100%'> "
				+ "    			                                                                                     <tbody> "
				+ "    			                                                                                       <tr> "
				+ "    			                                                                                         <td style='color:rgb(0,0,0);font-family:Helvetica,Arial,sans-serif;font-size:22px;line-height:22px;padding-bottom:10px;padding-top:45px;direction:ltr;text-align:left'>Dear ,</td> "
				+ "    			                                                                                       </tr> "
				+ "    			                                                                                       <tr> "
				+ "    			                                                                                         <td style='padding-top:15px;padding-bottom:15px;direction:ltr;text-align:left'> "
				+ "    			                                                                                           <div> "
				+ "    			                                                                                             <table border='0' cellpadding='0' cellspacing='0' align='left' style='border:none;border-collapse:collapse;border-spacing:0;max-width:538px;width:100%'> "
				+ "    			                                                                                               <tbody> "
				+ "    			                                                                                                 <tr> "
				+ "    			                                                                                                   <td align='left'  style='background-position:center left;background-repeat:no-repeat;font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'> "
				+ "    			                                                                                                   <td style='color:rgb(0,0,0);font-family:Helvetica,Arial,sans-serif;font-size:12px;line-height:22px;direction:ltr;text-align:left'>"
				+ bodymsg + "</td> "
				+ "    			                                                                                                   </td> "
				+ "    			                                                                                                 </tr> "
				+ "    			                                                                                               </tbody> "
				+ "    			                                                                                             </table> "
				+ "																											  <table border='0' cellpadding='0' cellspacing='0' align='left' style='border:none;border-collapse:collapse;border-spacing:0;max-width:538px;width:100%'> "
				+ "    			                                                                                               <tbody> "
				+ "    			                                                                                                 <tr> "
				+ "    			                                                                                                   <td align='left'  style='background-position:center left;background-repeat:no-repeat;font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'> "
				+
//    			"    			                                                                                                   <td style='color:rgb(0,0,0);font-family:Helvetica,Arial,sans-serif;font-size:12px;line-height:22px;direction:ltr;text-align:left'>Username :"+userRegistrationDTO.getUserName()+"</td> " + 
//    			"    			                                                                                                   </td> " + 
				"    			                                                                                                 </tr> "
				+ "																												  <tr> "
				+ "    			                                                                                                   <td align='left'  style='background-position:center left;background-repeat:no-repeat;font-size:1px;height:1px;line-height:1px;padding-left:0px!important;padding-right:0px!important;direction:ltr;text-align:left'> "
				+
				// " <td
				// style='color:rgb(0,0,0);font-family:Helvetica,Arial,sans-serif;font-size:12px;line-height:22px;direction:ltr;text-align:left'>Password
				// : "+userRegistrationDTO.getPassword()+"</td> " +
				"    			                                                                                                   </td> "
				+ "    			                                                                                                 </tr>"
				+ "    			                                                                                               </tbody> "
				+ "    			                                                                                             </table> "
				+ "    			                                                                                           </div> "
				+ "    			                                                                                         </td> "
				+ "    			                                                                                       </tr> "
				+ "    			                                                                                       <tr> "
				+ "    			                                                                                         <td style='direction:ltr;text-align:left'> "
				+ "    		"
				+ "    			                                                                                         </td> "
				+ "    			                                                                                       </tr> "
				+ "    			                                                                                     </tbody> "
				+ "    			                                                                                   </table> "
				+ "    			                                                                                 </td> "
				+ "    			                                                                               </tr> "
				+ "    			                                                                             </tbody> "
				+ "    			                                                                           </table> "
				+ "    			                                                                         </td> "
				+ "    			                                                                       </tr> "
				+ "    			                                                                     </tbody> "
				+ "    			                                                                   </table> "
				+ "    			                                                                 </td> "
				+ "    			                                                               </tr> "
				+ "    			                                                             </tbody> "
				+ "    			                                                           </table> "
				+ "    			                                                           <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                             <tbody> "
				+ "    			                                                               <tr> "
				+ "    			                                                                 <td align='left' style='background-color:rgb(0,136,0);padding-top:15px;padding-bottom:15px;direction:ltr;text-align:left'> "
				+ "    			                                                                   <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                     <tbody> "
				+ "    			                                                                       <tr> "
				+ "    			                                                                         <td style='text-align:center;font-size:0px;direction:ltr'> "
				+ "    			                                                                           <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;display:inline-block;max-width:none;min-width:208px;width:50%'> "
				+ "    			                                                                             <tbody> "
				+ "    			                                                                               <tr> "
				+ "    			                                                                                 <td style='padding:10px 0px 10px 0px;direction:ltr;text-align:left'> "
				+ "    			                                                                                   <table border='0' cellpadding='0' cellspacing='0' width='100%' align='left' style='border:none;border-collapse:collapse;border-spacing:0;table-layout:fixed;width:100%'> "
				+ "    			                                                                                     <tbody> "
				+ "    			                                                                                       <tr> "
				+ "    			                                                                                         <td style='padding-left:26px;padding-right:12px' align='center'></td> "
				+ "    			                                                                                         <td width='1' valign='top' style='direction:ltr;text-align:left'> "
				+ "    			                                                                                           <table border='0' cellpadding='0' cellspacing='0' width='100%' style='border:none;border-collapse:collapse;border-spacing:0;table-layout:fixed;width:100%'> "
				+ "    			                                                                                             <tbody> "
				+ "    			                                                                                               <tr> "
				+ "    			                                                                                                 <td height='20' width='1' style='direction:ltr;text-align:left'>&nbsp;</td> "
				+ "    			                                                                                               </tr> "
				+ "    			                                                                                             </tbody> "
				+ "    			                                                                                           </table> "
				+ "    			                                                                                         </td> "
				+ "    			                                                                                       </tr> "
				+ "    			                                                                                     </tbody> "
				+ "    			                                                                                   </table> "
				+ "    			                                                                                 </td> "
				+ "    			                                                                               </tr> "
				+ "    			                                                                             </tbody> "
				+ "    			                                                                           </table> "
				+ "    			                                                                         </td> "
				+ "    			                                                                       </tr> "
				+ "    			                                                                     </tbody> "
				+ "    			                                                                   </table> "
				+ "    			                                                                 </td> "
				+ "    			                                                               </tr> "
				+ "    			                                                             </tbody> "
				+ "    			                                                           </table> "
				+ "    			                                                           <table width='100%' border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                             <tbody> "
				+ "    			                                                               <tr> "
				+ "    			                                                                 <td align='left' style='background-color:#f1f1f1;padding:0px 14px 0px 14px;direction:ltr;text-align:left'> "
				+ "    			                                                                   <table border='0' cellpadding='0' cellspacing='0' style='border:none;border-collapse:collapse;border-spacing:0;width:100%'> "
				+ "    			                                                                     <tbody> "
				+ "    			                                                                       <tr> "
				+ "    			                                                                         <td style='direction:ltr;text-align:left'> "
				+ "    			                                                                           <table border='0' cellpadding='0' cellspacing='0' align='left' style='border:none;border-collapse:collapse;border-spacing:0;max-width:616px;width:100%'> "
				+ "    			                                                                             <tbody> "
				+ "    			                                                                               <tr> "
				+ "    			                                                                                 <td style='padding-left:12px;padding-right:12px;direction:ltr;text-align:left'> "
				+ "    			                                                                                   <table border='0' cellpadding='0' cellspacing='0' width='100%' align='left' style='border:none;border-collapse:collapse;border-spacing:0;table-layout:fixed;width:100%'> "
				+ "    			                                                                                     <tbody> "
				+ "    			                                                                                       <tr> "
				+ "    			                                                                                         <td style='color:rgb(0,0,0);font-family:Helvetica,Arial,sans-serif;font-size:12px;line-height:20px;padding-bottom:30px;padding-top:30px;direction:ltr;text-align:left'> Wishing you good health always </td> "
				+ "    			                                                                                       </tr> "
				+ "    			                                                                                     </tbody> "
				+ "    			                                                                                   </table> "
				+ "    			                                                                                 </td> "
				+ "    			                                                                               </tr> "
				+ "    			                                                                             </tbody> "
				+ "    			                                                                           </table> "
				+ "    			                                                                         </td> "
				+ "    			                                                                       </tr> "
				+ "    			                                                                     </tbody> "
				+ "    			                                                                   </table> "
				+ "    			                                                                 </td> "
				+ "    			                                                               </tr> "
				+ "    			                                                             </tbody> "
				+ "    			                                                           </table> "
				+ "    			                                                         </td> "
				+ "    			                                                       </tr> "
				+ "    			                                                     </tbody> "
				+ "    			                                                   </table> "
				+ "    			                                                 </td> "
				+ "    			                                               </tr> "
				+ "    			                                             </tbody> "
				+ "    			                                           </table> "
				+ "    			                                         </td> "
				+ "    			                                       </tr> "
				+ "    			                                     </tbody> "
				+ "    			                                   </table> "
				+ "    			                                 </td> "
				+ "    			                               </tr> "
				+ "    			                             </tbody> "
				+ "    			                           </table> " + "    			                         </td> "
				+ "    			                       </tr> " + "    			                     </tbody> "
				+ "    			                   </table> " + "    			                 </td> "
				+ "    			               </tr> " + "    			             </tbody> "
				+ "    			           </table> " + "    			         </td> "
				+ "    			       </tr> " + "    			     </tbody> " + "    			   </table> "
				+ "    			    " + "    			   <div class='yj6qo'></div> "
				+ "    			   <div class='adL'></div> " + "    			 </div>";

		MailSender.sendMail(ContextConstants.smtpPort, ContextConstants.smtpHostname, ContextConstants.smtpFromAddress,
				ContextConstants.smtpPassword, ContextConstants.smtpContentType,
				"Welcome to " + "Sayone Technology" + "!", mailContent, files, to, bcc, cc);

	}

}
